apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 1Gi   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: master
        image: linuxcloudops/jenkins-docker 
        ports:
        - containerPort: 8080
        - containerPort: 50000
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
      restartPolicy: Always
      volumes:
        - name: jenkins
          persistentVolumeClaim:
          claimName: jenkins-pvc 
        - name: docker-sock-volume
          hostPath:
            path: /var/run/docker.sock
            type: File
